CREATE TABLE IF NOT EXISTS PROJECTS_USERS (
   PROJECT_ID INT8 NOT NULL,
   USER_ID INT8 NOT NULL,
   PRIMARY KEY (PROJECT_ID, USER_ID),
   CONSTRAINT fk_user_id FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON UPDATE CASCADE,
   CONSTRAINT fk_project_id FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID) ON UPDATE CASCADE
);