DROP TABLE IF EXISTS PROJECTS_USERS;

CREATE TABLE PROJECTS_USERS (
  PROJECT_ID    int REFERENCES PROJECT(ID) ON UPDATE CASCADE 
, USER_ID int REFERENCES USERS(ID) ON UPDATE CASCADE
, CONSTRAINT user_project_pkey PRIMARY KEY (PROJECT_ID, USER_ID)  
);

