CREATE TABLE PROJECT
(
  ID BIGSERIAL PRIMARY KEY,
  PROJECT_NAME VARCHAR(255),
  DESCRIPTION VARCHAR(500)
);

CREATE TYPE status AS ENUM ('Open', 'InProgress', 'Reopened', 'Resolved', 'Closed'); 
CREATE TYPE priority AS ENUM ( 'LOW', 'MEDIUM','HIGH'); 

CREATE TABLE BUG (
  ID BIGSERIAL primary key,
  PROJECT_ID BIGSERIAL NOT NULL references PROJECT(ID),
  assignee_id BIGSERIAL NOT NULL,
  assigner_id BIGSERIAL NOT NULL,
  BUG_DESCRIPTION VARCHAR(500),
  RESOLUTION_SUMMARY VARCHAR(500),
  STATUS status,
  PRIORITY priority,
  CREATED_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT fk_assignee FOREIGN KEY (assignee_id) REFERENCES USERS(id),
  CONSTRAINT fk_assigner FOREIGN KEY (assigner_id) REFERENCES USERS(id)
);

CREATE TABLE COMMENTS(
  ID BIGSERIAL primary key,
  BUG_ID bigint NOT NULL,
  MESSAGE VARCHAR(500),
  CREATED_AT DATE NOT NULL DEFAULT CURRENT_DATE,
  COMMENTER_ID bigint NOT NULL,
  FOREIGN KEY (BUG_ID) REFERENCES BUG(ID) ON DELETE CASCADE,
  FOREIGN KEY (COMMENTER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
)