INSERT INTO AUTHORITY(ID, NAME)
  VALUES (3, 'ROLE_PROJECT_MANAGER');
  
INSERT INTO ROLE(ID, ROLE_NAME)
  VALUES (3, 'PROJECT_MANAGER');
  
INSERT INTO ROLES_AUTHORITIES(ROLE_ID, AUTHORITY_ID) VALUES (3, 3);