ALTER TABLE BUG ADD COLUMN assignee_id BIGSERIAL;
ALTER TABLE BUG ADD
CONSTRAINT fk_assignee FOREIGN KEY (assignee_id) REFERENCES USERS(id);

ALTER TABLE BUG ADD COLUMN assigner_id BIGSERIAL;
ALTER TABLE BUG ADD
CONSTRAINT fk_assigner FOREIGN KEY (assigner_id) REFERENCES USERS(id);